// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.classes.SpikeController;
import frc.robot.subsystems.Drivetrain;

/**
 *
 */
public class OrientedDrive extends Command {
    private final Drivetrain m_drivetrain;
    private final SpikeController m_controller;
    private final boolean m_fieldOriented;

    private final double MAX_TRANSLATION_VELOCITY = 3.0d;
    private final double MAX_ROTATION_VELOCITY = 3.0d;

    public OrientedDrive(Drivetrain drivetrain, SpikeController controller, boolean fieldOriented) {
        m_drivetrain = drivetrain;
        m_fieldOriented = fieldOriented;
        m_controller = controller;

        addRequirements(m_drivetrain);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        Translation2d robotTranslation = new Translation2d(m_controller.getRightY(), m_controller.getRightX());
        
        double rotationSpeed = m_controller.getLeftX() * MAX_ROTATION_VELOCITY;

        m_drivetrain.drive(robotTranslation, rotationSpeed, m_fieldOriented, false);
    }
}
